"""FFW SH5 control limits."""

FFW_SH5_LIFT_JOINT_NAME = "lift_joint"
FFW_SH5_LIFT_POSITION_SCALE = 0.5

FFW_SH5_SWERVE_STEERING_LIMIT_LOWER = -1.570796
FFW_SH5_SWERVE_STEERING_LIMIT_UPPER = 1.570796
FFW_SH5_SWERVE_WHEEL_SPEED_LIMIT_LOWER = -50.0
FFW_SH5_SWERVE_WHEEL_SPEED_LIMIT_UPPER = 50.0
