[package]

# Semantic Versioning is used: https://semver.org/
version = "2.0.3"

# Description
title =  "cyclo_lab Tasks"
description=""
readme  = "README.md"
repository = "https://github.com/ROBOTIS-GIT/cyclo_lab.git"
category = "robotics"
keywords = ["extension", "cyclo_lab", "isaaclab"]

[dependencies]
"isaaclab" = {}
"isaaclab_newton" = {}

[core]
reloadable = false

# Main python module this extension provides.
[[python.module]]
name = "cyclo_lab"
