"""FFW SG2 control limits."""

# Use the shipped SG2 ROS controller geometry and steering behavior. Keep a
# simulator-side command acceleration limit because Isaac velocity targets do not
# model the real base motor/current ramp and can otherwise tip the robot.
FFW_SG2_SWERVE_STEERING_LIMIT_LOWER = -6.28
FFW_SG2_SWERVE_STEERING_LIMIT_UPPER = 6.28
FFW_SG2_SWERVE_STEERING_ANGULAR_VELOCITY_LIMIT = 100.0
FFW_SG2_SWERVE_DRIVE_SPEED_SCALE = 1.0
FFW_SG2_SWERVE_ENABLED_SPEED_LIMITS = True
FFW_SG2_SWERVE_LINEAR_ACCELERATION_LIMIT = 1.5
FFW_SG2_SWERVE_ANGULAR_ACCELERATION_LIMIT = 2.5
FFW_SG2_SWERVE_WHEEL_SPEED_LIMIT_LOWER = -50.0
FFW_SG2_SWERVE_WHEEL_SPEED_LIMIT_UPPER = 50.0
FFW_SG2_SWERVE_STEERING_ALIGNMENT_ANGLE_ERROR_THRESHOLD = 1.0
FFW_SG2_SWERVE_STEERING_ALIGNMENT_START_ANGLE_ERROR_THRESHOLD = 0.01
FFW_SG2_SWERVE_STEERING_ALIGNMENT_START_SPEED_ERROR_THRESHOLD = 0.1
FFW_SG2_SWERVE_ENABLED_WHEEL_SATURATION_SCALING = True

FFW_SG2_LIFT_POSITION_LOWER = -0.5
FFW_SG2_LIFT_POSITION_UPPER = 0.0


def clamp_lift_position(position: float) -> float:
    return max(FFW_SG2_LIFT_POSITION_LOWER, min(float(position), FFW_SG2_LIFT_POSITION_UPPER))
